/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define RCC_BASE   0x40023800UL
#define GPIOA_BASE 0x40020000UL

#define RCC_AHB1ENR (*((volatile unsigned int *)(RCC_BASE + 0x30)))
#define GPIOA_MODER (*((volatile unsigned int *)(GPIOA_BASE + 0x00)))
#define GPIOA_ODR   (*((volatile unsigned int *)(GPIOA_BASE + 0x14)))

int main(void)
{
	// Step 1: Enable GPIOA clock
	// Bit 0 of AHB1ENR controls GPIOA clock
	RCC_AHB1ENR |= (1U << 0);

	// Step 2: Set PA5 as output
	// PA5 uses bits 11:10 in MODER
	// Clear both bits first, then set bit 10 to make it "01" = output
	GPIOA_MODER &= ~(3U << 10);  // clear bits 11:10
	GPIOA_MODER |=  (1U << 10);  // set bit 10 → output mode

	// Step 3: Blink forever
	while(1)
	{
		// Toggle PA5 high
		GPIOA_ODR |= (1U << 5);

		// Crude delay
		for(volatile int i = 0; i < 500000; i++);

		// Toggle PA5 low
		GPIOA_ODR &= ~(1U << 5);

		// Crude delay
		for(volatile int i = 0; i < 500000; i++);
	}
}
